# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pr:
- master
- 202???
- 201???

trigger:
  batch: true
  branches:
    include:
    - master
    - 202???
    - 201???

# this part need to be set in UI
schedules:
- cron: "0 0 * * 6"
  displayName: Weekly build
  branches:
    include:
    - master
    - 202???
    - 201???
  always: true

parameters:
  - name: debian_version
    type: string
    default: bookworm

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      pool: sonicso1ES-amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      common_lib_artifact_name: common-lib
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}
      dash_artifact_name: sonic-dash-api
      artifact_name: sonic-swss-${{ parameters.debian_version }}
      debian_version: ${{ parameters.debian_version }}
      archive_pytests: true
      archive_gcov: true

- stage: BuildAsan
  dependsOn: []
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      pool: sonicso1ES-amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      common_lib_artifact_name: common-lib
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}
      dash_artifact_name: sonic-dash-api
      artifact_name: sonic-swss-asan-${{ parameters.debian_version }}
      debian_version: ${{ parameters.debian_version }}
      asan: true

- stage: BuildArm
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      timeout: 240
      pool: sonicso1ES-armhf
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      common_lib_artifact_name: common-lib.armhf
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}.armhf
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}.armhf
      dash_artifact_name: sonic-dash-api.armhf
      artifact_name: sonic-swss-${{ parameters.debian_version }}.armhf
      debian_version: ${{ parameters.debian_version }}
      archive_gcov: false

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 240
      pool: sonicso1ES-arm64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      common_lib_artifact_name: common-lib.arm64
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}.arm64
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}.arm64
      dash_artifact_name: sonic-dash-api.arm64
      artifact_name: sonic-swss-${{ parameters.debian_version }}.arm64
      debian_version: ${{ parameters.debian_version }}
      archive_gcov: false

- stage: BuildTrixie
  dependsOn: BuildArm
  condition: succeeded('BuildArm')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      pool: sonicso1ES-amd64
      sonic_slave: sonic-slave-trixie
      common_lib_artifact_name: common-lib
      swss_common_artifact_name: sonic-swss-common-trixie
      sairedis_artifact_name: sonic-sairedis-trixie
      dash_artifact_name: sonic-dash-api-trixie
      artifact_name: sonic-swss-trixie
      debian_version: trixie
      archive_gcov: false

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      timeout: 240
      pool: sonicso1ES-armhf
      sonic_slave: sonic-slave-trixie
      common_lib_artifact_name: common-lib.armhf
      swss_common_artifact_name: sonic-swss-common-trixie.armhf
      sairedis_artifact_name: sonic-sairedis-trixie.armhf
      dash_artifact_name: sonic-dash-api-trixie.armhf
      artifact_name: sonic-swss-trixie.armhf
      debian_version: trixie
      archive_gcov: false

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 240
      pool: sonicso1ES-arm64
      sonic_slave: sonic-slave-trixie
      common_lib_artifact_name: common-lib.arm64
      swss_common_artifact_name: sonic-swss-common-trixie.arm64
      sairedis_artifact_name: sonic-sairedis-trixie.arm64
      dash_artifact_name: sonic-dash-api-trixie.arm64
      artifact_name: sonic-swss-trixie.arm64
      debian_version: trixie
      archive_gcov: false

- stage: BuildDocker
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}
      swss_artifact_name: sonic-swss-${{ parameters.debian_version }}
      debian_version: ${{ parameters.debian_version }}
      artifact_name: docker-sonic-vs

- stage: BuildDockerAsan
  dependsOn: BuildAsan
  condition: succeeded('BuildAsan')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}
      swss_artifact_name: sonic-swss-asan-${{ parameters.debian_version }}
      artifact_name: docker-sonic-vs-asan
      debian_version: ${{ parameters.debian_version }}
      asan: true

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log
      gcov_artifact_name: sonic-gcov
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      archive_gcov: true
      debian_version: ${{ parameters.debian_version }}

- stage: TestAsan
  dependsOn: BuildDockerAsan
  condition: succeeded('BuildDockerAsan')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log-asan
      gcov_artifact_name: sonic-gcov
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      docker_sonic_vs_name: docker-sonic-vs-asan
      asan: true
      debian_version: ${{ parameters.debian_version }}

- stage: Gcov
  condition: false
  dependsOn: Test
  jobs:
  - template: .azure-pipelines/gcov.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-${{ parameters.debian_version }}
      swss_common_artifact_name: sonic-swss-common-${{ parameters.debian_version }}
      sairedis_artifact_name: sonic-sairedis-${{ parameters.debian_version }}
      swss_artifact_name: sonic-swss-${{ parameters.debian_version }}
      artifact_name: sonic-gcov
      archive_gcov: true
